import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(BASE_DIR, "src")
OUTPUT_MAIN = os.path.join(BASE_DIR, "main.lua")
OUTPUT_SOURCE = os.path.join(BASE_DIR, "main_source.lua")

def read_file(path):
    if not os.path.exists(path):
        print(f"[!] Warning: missing {path}")
        return ""
    with open(path, "r", encoding="utf-8-sig") as f:
        return f.read().strip()

def read_module(base, mod_name):
    sub_dir = os.path.join(base, mod_name)
    single_file = os.path.join(base, f"{mod_name}.lua")
    if os.path.isdir(sub_dir):
        files = sorted([f for f in os.listdir(sub_dir) if f.endswith(".lua")])
        chunks = []
        for f in files:
            chunks.append(read_file(os.path.join(sub_dir, f)))
        return "\n\n".join(chunks)
    elif os.path.isfile(single_file):
        return read_file(single_file)
    return ""

bypass = read_file(os.path.join(SRC_DIR, "core", "bypass.lua"))
ui_lib = read_file(os.path.join(SRC_DIR, "core", "ui_library.lua"))
automation = read_file(os.path.join(SRC_DIR, "core", "automation.lua"))

main_funcs = read_module(os.path.join(SRC_DIR, "functions"), "main")
misc_funcs = read_module(os.path.join(SRC_DIR, "functions"), "misc")

main_tab = read_file(os.path.join(SRC_DIR, "tabs", "main.lua"))
misc_tab = read_file(os.path.join(SRC_DIR, "tabs", "misc.lua"))
settings_tab = read_file(os.path.join(SRC_DIR, "tabs", "settings.lua"))

bundled = f"""--[[
    Steal An Egg Hub - DKHUB Standalone Script
    Game: Steal a Egg (Place ID: 108053424714724)
    Protected with Anti-Cheat (BAC-7517) Bypass & Universal Delta / Mobile Support
    Generated by DKHUB Bundler Tool
--]]

-- Ensure game is loaded
if not game:IsLoaded() then
    pcall(function() game.Loaded:Wait() end)
end

local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local CoreGui = game:GetService("CoreGui")
local TweenService = game:GetService("TweenService")
local RunService = game:GetService("RunService")

local LocalPlayer = Players.LocalPlayer
if not LocalPlayer then
    LocalPlayer = Players:FindFirstChildWhichIsA("Player")
    if not LocalPlayer then
        pcall(function() LocalPlayer = Players.PlayerAdded:Wait() end)
    end
end

-- 1. Initialize Anti-Cheat Bypass first before anything else
local Bypass = (function()
{bypass}
end)()
pcall(function() Bypass.Init() end)

-- 2. Initialize UI Library
local UILibrary = (function()
{ui_lib}
end)()

-- 3. Initialize Core Automation Engine
local Automation = (function()
{automation}
end)()

-- Register master clean unloader function globally
local _env = (typeof(getgenv) == "function" and getgenv()) or _G
if _env then
    _env._StealAnEgg_CleanUnload = function()
        pcall(function()
            if Automation and typeof(Automation.Unload) == "function" then
                Automation.Unload(UILibrary)
            end
        end)
    end
end

-- 4. Initialize Feature Functions
local MainFunctions = (function()
{main_funcs}
end)()

local MiscFunctions = (function()
{misc_funcs}
end)()

-- 5. Construct Main Window with safe wrapper
local function _initHub()
    local Window = UILibrary:CreateWindow({{
        Title = "Steal An Egg Hub | DKHUB",
        SubTitle = "v1.0 Standalone",
        MinimizeKey = Enum.KeyCode.RightControl
    }})

    if not Window then
        warn("[Steal An Egg Hub]: Failed to create main window.")
        return
    end

    local Tabs = {{
        Main        = Window:AddTab({{ Title = "Main", Icon = "rbxassetid://10723407389" }}),
        Misc        = Window:AddTab({{ Title = "Misc", Icon = "rbxassetid://10734975692" }}),
        Settings    = Window:AddTab({{ Title = "Settings", Icon = "rbxassetid://10734950309" }})
    }}

    local function _safeRunTab(name, fn)
        local ok, err = pcall(fn)
        if not ok then warn("[Steal An Egg Hub Tab Error - " .. tostring(name) .. "]: " .. tostring(err)) end
    end

    _safeRunTab("Main", function() local _m = (function()
{main_tab}
    end)(); _m(Tabs.Main, Automation, MainFunctions, MiscFunctions, UILibrary); end)

    _safeRunTab("Misc", function() local _m = (function()
{misc_tab}
    end)(); _m(Tabs.Misc, Automation, MiscFunctions, MainFunctions, UILibrary); end)

    _safeRunTab("Settings", function() local _m = (function()
{settings_tab}
    end)(); _m(Tabs.Settings, Automation, MainFunctions, Window, UILibrary); end)

    Window:SelectTab(1)

    -- Load saved config if present
    pcall(function() Automation.LoadConfig() end)

    UILibrary:Notify({{
        Title = "Steal An Egg Hub Loaded",
        Content = "All features & Anti-Cheat Protection loaded successfully.",
        Duration = 5
    }})

    -- Check Auto Performance flags on load
    pcall(function()
        if Automation.Flags.AutoFullPerf then
            Automation.FullPerformanceMode()
        end
        if Automation.Flags.Disable3DRendering then
            Automation.Toggle3DRendering(false)
        end
    end)

    print("[Steal An Egg Hub]: UI & BAC Protection loaded successfully on " .. (UserInputService.TouchEnabled and "Mobile / Delta" or "Desktop") .. "!")
end

local okInit, errInit = pcall(_initHub)
if not okInit then
    warn("[Steal An Egg Hub Fatal Error]: " .. tostring(errInit))
end
"""

with open(OUTPUT_SOURCE, "w", encoding="utf-8") as f:
    f.write(bundled)

with open(OUTPUT_MAIN, "w", encoding="utf-8") as f:
    f.write(bundled)

print(f"[+] Successfully bundled {len(bundled)} bytes into main.lua and main_source.lua")
